console.log("salut")
alert("hello")
console.log("salut")
console.log("salut")
console.log("salut")
console.log("salut")
alert("Attention danger")
console.log("je dis ")
alert("travail de groupe ")
console.log("salut")